name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: xxx
    steps:
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: echo ${{ runner.name	 }}

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v2.10.0

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }} 
        
    - name: Build and Push Images
      id: buildx
      uses: docker/build-push-action@v4.1.1

      with:
        context: .
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        tags: |
          admibo/clash_vpn:latest
          admibo/clash_vpn:${{ github.event.head_commit.message }}
    
